version: "3.8"

services:
  db:
    image: mariadb:latest
    container_name: ptt_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ptt_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

#redis已存在 先暫時不加
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

# celery worker、celery beat先不加 不確定是否有影響
  celery_worker:
    build: .
    container_name: celery_worker
    restart: always
    depends_on:
      - redis
      - db
    command: celery -A tools.tasks worker --loglevel=info

  celery_beat:
    build: .
    container_name: celery_beat
    restart: always
    depends_on:
      - celery_worker
    command: celery -A tools.tasks beat --loglevel=info

volumes:
  mariadb_data:
